[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push && node prisma/seed.js && node src/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
